language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://wordpress.dev WP_TEST_USER=test WP_TEST_USER_PASS=test WP_TEST_URL=127.0.0.1:80

install:
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer self-update
  - composer install --prefer-dist

before_script:
  # clone the repo containing WordPress installation scripts
  # credit: https://github.com/Koodimonni/wordpress-test-template
  - git clone https://github.com/lucatume/wordpress-test-template wp-tests

  # install WordPress in /tmp/wordpress, assumes it will be served on localhost:12000
  - bash wp-tests/bin/install-wp-tests.sh wp-tests root '' localhost $WP_VERSION

  # update and install apache2 packages
  # credit: https://www.marcus-povey.co.uk/2016/02/16/travisci-with-php-7-on-apache-php-fpm/
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi make
  - sudo apt-get install -y --force-yes php5-dev php-pear php5-mysql php5-curl php5-gd php5-json php5-sqlite php5-pgsql
  - sudo a2enmod headers

  # Enable php-fpm
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%WP_DIR%?/tmp/wordpress?g" --in-place /etc/apache2/sites-available/default

  # Restart services
  - sudo service apache2 restart

script:
  - cat /etc/apache2/sites-available/default
  - sudo apache2ctl -S
#  - curl http://127.0.0.1:80
#  - php ./vendor/bin/codecept run unit
#  - php ./vendor/bin/codecept run wpmodule AdminAccessCest:it_should_be_able_to_visit_the_admin_area_when_unlogged -vvv
  - php ./vendor/bin/codecept run acceptance HomepageCept -vvv
