sudo: required

language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

install:
  - composer install --prefer-dist

before_script:
  # install wp-cli
  - cd /tmp
  - mkdir tools
  - cd tools
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar

  # download wordpress
  - cd /tmp
  - mkdir wordpress
  - cd /tmp/wordpress
  - /tmp/tools/wp-cli.phar core download

  # install wordpress
  - /tmp/tools/wp-cli.phar core config --dbname=test --dbuser=root --dbpass='' --dbhost=localhost --dbprefix=acceptance_ --skip-salts
  - /tmp/tools/wp-cli.phar core install --url=localhost --title=Test --admin_user=admin --admin_password=admin --admin_email=admin@test.com
  - /tmp/tools/wp-cli.phar core version

  # update and install apache2 packages
  # credit: https://www.marcus-povey.co.uk/2016/02/16/travisci-with-php-7-on-apache-php-fpm/
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi make
  - sudo apt-get install -y --force-yes php5-dev php-pear php5-mysql php5-curl php5-gd php5-json php5-sqlite php5-pgsql
  - sudo a2enmod headers

  # Enable php-fpm
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Configure apache virtual hosts
  - sudo cp -f $TRAVIS_BUILD_DIR/build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%WP_DIR%?/tmp/wordpress?g" --in-place /etc/apache2/sites-available/default

  # Restart services
  - sudo service apache2 restart

script:
  # - cat /etc/apache2/sites-available/default
  # - sudo apache2ctl -S
   # - php ./vendor/bin/codecept run unit
   # - php ./vendor/bin/codecept run wpmodule AdminAccessCest:it_should_be_able_to_visit_the_admin_area_when_unlogged -vvv
  - php $TRAVIS_BUILD_DIR/vendor/bin/codecept run acceptance HomepageCept -vvv
