sudo: false

language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

addons:
  apt:
    packages:
    - apache2
    - libapache2-mod-php5
    - php5-curl
    - php5-mysql
    - php5-intl

install:
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer self-update
  - composer install --prefer-dist

before_script:
  # install WordPress in /tmp/wordpress and serve it on http://localhost:12000
  - git clone https://github.com/lucatume/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION
  # create a wordpress.dev virtual host in Apache served from the /tmp/wordpress folder
  - sed -i -e "s,/var/www,/tmp/wordpress,g" /etc/apache2/sites-available/default
  - sed -i -e "/DocumentRoot/i\ServerName wordpress.dev" /etc/apache2/sites-available/default
  - echo "127.0.0.1 wordpress.dev" | sudo tee -a /etc/hosts
  - /etc/init.d/apache2 restart

script:
#  - php ./vendor/bin/codecept run unit
#  - php ./vendor/bin/codecept run wpmodule AdminAccessCest:it_should_be_able_to_visit_the_admin_area_when_unlogged -vvv
  - php ./vendor/bin/codecept run acceptance HomepageCept -vvv
