sudo: required

language: php

notifications:
  email: false

php:
  - '5.6'
  - '7.0'

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - wpDbName=test wpLoaderDbName=wploader wpDbPrefix=wp_ wpUrl=wordpress.dev wpAdminUsername=admin wpAdminPassword=admin wpSubdomain1=test1 wpSubdomain1Title="Test Subdomain 1" wpSubdomain2=test2 wpSubdomain2Title="Test Subdomain 2"

before_install:
  - mysql -e "create database IF NOT EXISTS $wpDbName;" -uroot
  - mysql -e "create database IF NOT EXISTS $wpLoaderDbName;" -uroot

install:
  - composer update --prefer-dist

before_script:
  # set up folders
  - mkdir -p $HOME/tools /tmp/wordpress

  # install Apache setup script
  - git clone https://github.com/lucatume/travis-apache-setup.git /tmp/tools/travis-apache-setup
  - chmod +x /tmp/tools/travis-apache-setup/apache-setup.sh
  - chmod +x /tmp/tools/travis-apache-setup/wp-install.sh
  - ln -s /tmp/tools/travis-apache-setup/apache-setup.sh /tmp/tools/apache-setup
  - ln -s /tmp/tools/travis-apache-setup/wp-install.sh /tmp/tools/wp-install

  # download and install WordPress
  - wp-install --dir=/tmp/wordpress --dbname="$wpDbName" --dbuser="root" --dbpass="" --dbprefix=wp_ --domain="wordpress.dev" --title="Test" --base=/ --admin_user=admin --admin_password=admin --admin_email=admin@wordpress.dev --theme=twentysixteen --multisite --subdomains --empty 
  - cd /tmp/wordpress
  - wp site create --slug=$wpSubdomain1 --title="$wpSubdomain1Title"
  - wp site create --slug=$wpSubdomain2 --title="$wpSubdomain2Title"

  # export a dump of the just installed database to the _data folder
  - cd /tmp/wordpress
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql

  # set up Apache virtual host
  - sudo env "PATH=$PATH" apache-setup --host="127.0.0.1" --url="$wpUrl" --dir="/tmp/wordpress" 

  # Get back to Travis build dir
  - cd $TRAVIS_BUILD_DIR

script:
  - codecept run
