sudo: required

language: php

notifications:
  email: false

php:
  - '5.6'
#  - '7.0'
#  - '7.1'
#  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: wpVersion=nightly

services:
  - mysql

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files

env:
  global:
    - wpFolder="/tmp/wordpress"
    - wpDbName="test"
    - wpLoaderDbName="wploader"
    - wpDbPrefix="wp_"
    - wpUrl="http://wp.dev:8080"
    - wpAdminUsername="admin"
    - wpAdminPassword="admin"
    - wpSubdomain1="test1"
    - wpSubdomain1Title="Test Subdomain 1"
    - wpSubdomain2="test2"
    - wpSubdomain2Title="Test Subdomain 2"
  matrix:
    - wpVersion=latest
    - wpVersion=nightly

before_install:
  # create the databases that will be used in the tests
  - mysql -e "create database IF NOT EXISTS $wpDbName;" -uroot
  - mysql -e "create database IF NOT EXISTS $wpLoaderDbName;" -uroot
  # set up folders
  - mkdir -p $wpFolder
  - mkdir tools
  # install wp-cli in the `tools` folder
  - wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P $(pwd)/tools/
  - chmod +x tools/wp-cli.phar && mv tools/wp-cli.phar tools/wp
  # install Tang Rufus package
  - composer global require -n --prefer-dist "typisttech/travis-nginx-wordpress:^1.0.0"
  # append the `tools` folder to the PATH
  - export PATH=$PATH:$(pwd)/tools
  # prepend the `vendor/bin` folder the PATH
  - export PATH=vendor/bin:$PATH

install:
  - composer update --prefer-dist
  # install WordPress in the `wordpress` folder
  - cd $wpFolder
  - wp core download
  - wp config create --dbname="$wpDbName" --dbuser="root" --dbpass="" --dbhost="127.0.0.1" --dbprefix="$wpDbPrefix"
  - wp core multisite-install --url="$wpUrl" --base="/" --subdomains --title="Test" --admin_user="$wpAdminUsername" --admin_password="$wpAdminPassword" --admin_email="admin@wp.dev" --skip-email
  - wp rewrite structure '/%postname%/' --hard
  - wp site create --slug="$wpSubdomain1" --title="$wpSubdomain1Title"
  - wp site create --slug="$wpSubdomain2" --title="$wpSubdomain2Title"
  # update WordPress database to avoid prompts
  - wp core update-db --network
  # export a dump of the just installed database to the _data folder
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql
  # get back to the build folder
  - cd $TRAVIS_BUILD_DIR
  # install Nginx to serve WordPress on `http://wp.dev:8080` from `/tmp/wordpress`
  - tnw-install-nginx

before_script:

script:
#  - codecept run unit
  - codecept run acceptance -vvv
  - codecept run phantomjs -vvv
#  - codecept run functional
#  - codecept run climodule
#  - codecept run wpmodule
#  - codecept run wploadersuite
#  - codecept run muloader
#  - codecept run cli
