sudo: required

language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "create database IF NOT EXISTS wploader;" -uroot

install:
  - composer update --prefer-dist

before_script:
  # set up folders
  - mkdir -p /tmp/tools
  - mkdir -p /tmp/wordpress

  # install wp-cli
  - wget -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P /tmp/tools/
  - chmod +x /tmp/tools/wp-cli.phar

  # download wordpress
  - cd /tmp/wordpress
  - /tmp/tools/wp-cli.phar core download

  # install WordPress
  - /tmp/tools/wp-cli.phar core config --dbname=test --dbuser=root --dbpass='' --dbhost=localhost --dbprefix=wp_ --skip-salts
  - /tmp/tools/wp-cli.phar core multisite-install --url=wordpress.dev --base=/ --title=Test --admin_user=admin --admin_password=admin --admin_email=admin@test.com --subdomains --skip-email
  - /tmp/tools/wp-cli.phar site create --slug=test1 --title="Test Subdomain 1"
  - /tmp/tools/wp-cli.phar site create --slug=test2 --title="Test Subdomain 2"
  - /tmp/tools/wp-cli.phar core version

  # export a dump of the just installed database to the _data folder
  - /tmp/tools/wp-cli.phar db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql

  # update and install apache2 packages
  # credit: https://www.marcus-povey.co.uk/2016/02/16/travisci-with-php-7-on-apache-php-fpm/
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi make
  - sudo apt-get install -y --force-yes php5-dev php-pear php5-mysql php5-curl php5-gd php5-json php5-sqlite php5-pgsql
  - sudo a2enmod headers

  # Enable php-fpm
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp $TRAVIS_BUILD_DIR/build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Configure apache virtual hosts
  - sudo cp -f $TRAVIS_BUILD_DIR/build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%WP_DIR%?/tmp/wordpress?g" --in-place /etc/apache2/sites-available/default
  - echo '127.0.0.1 wordpress.dev' | sudo tee --append /etc/hosts > /dev/null

  # Restart services
  - sudo service apache2 restart

  # Get back to Travis build dir
  - cd $TRAVIS_BUILD_DIR

script:
  - php vendor/bin/codecept run
