language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://wordpress.dev WP_TEST_USER=test WP_TEST_USER_PASS=test

install:
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer self-update
  - composer install --prefer-dist

before_script:
  # install WordPress in /tmp/wordpress
  - git clone https://github.com/lucatume/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh wp-tests root '' localhost $WP_VERSION
  # update apm sources
  - sudo apt-get update
  # install Apache 2.2 server
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm in Apache
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # download virtual host script
  - curl https://gist.github.com/fideloper/2710970/raw/cbe308f44bfd299a3f410bb1a06aa67a2753763a/vhost.sh > vhost
  - sudo chmod guo+x vhost
  - sudo mv vhost /usr/local/bin
  # enable the wordpress.dev virtual host
  - sudo vhost -d /tmp/wordpress -s wordpress.dev
  - echo "127.0.0.1 wordpress.dev"  | sudo tee -a /etc/hosts
  # list the enabled sites
  - sudo ls -la /etc/apache2/sites-enables
  - sudo apache2ctl -S

script:
#  - php ./vendor/bin/codecept run unit
#  - php ./vendor/bin/codecept run wpmodule AdminAccessCest:it_should_be_able_to_visit_the_admin_area_when_unlogged -vvv
#  - cat /etc/apache2/sites-available/default
  - curl wordpress.dev
#  - php ./vendor/bin/codecept run acceptance HomepageCept -vvv
