language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://wordpress.dev WP_TEST_USER=test WP_TEST_USER_PASS=test

install:
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer self-update
  - composer install --prefer-dist

before_script:
  # install WordPress in /tmp/wordpress
  - git clone https://github.com/lucatume/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh wp-tests root '' localhost $WP_VERSION
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?/etc/apache2/%TRAVIS_BUILD_DIR%?%/tmp/wordpress/?g" --in-place /etc/apache2/sites-available/default
  - sudo cat /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts

script:
#  - php ./vendor/bin/codecept run unit
#  - php ./vendor/bin/codecept run wpmodule AdminAccessCest:it_should_be_able_to_visit_the_admin_area_when_unlogged -vvv
  - cat /etc/apache2/sites-available/default
  - curl wordpress.dev
#  - php ./vendor/bin/codecept run acceptance HomepageCept -vvv
