version: "3.9"
networks:
  test:
    name: wpbrowser_php_${PHP_VERSION:-8.0}
services:
  database:
    container_name: wpbrowser_php_${PHP_VERSION:-8.0}_database
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    healthcheck:
      test: [ "CMD", "mysqlshow", "-uroot", "-ppassword",  "wordpress" ]
      interval: 1s
      timeout: 1s
      retries: 30
    networks:
      - test
    tmpfs:
      - /var/lib/mysql
  wordpress:
    container_name: wpbrowser_php_${PHP_VERSION:-8.0}_wordpress
    user: "${USER_UID}:${USER_GID}"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    image: wp-browser-wordpress:php${PHP_VERSION:-8.0}-apache
    build:
      context: ./config/containers/php
      args:
        PHP_VERSION: "${PHP_VERSION:-8.0}"
        USER_UID: "${USER_UID:-33}"
        USER_GID: "${USER_GID:-www-data}"
        USER_NAME: "${USER_NAME:-www-data}"
        TARGET: "wordpress"
    depends_on:
      database:
        condition: service_healthy
    networks:
      test:
        aliases:
          - wordpress.test
          - one.wordpress.test
          - two.wordpress.test
          - test1.wordpress.test
          - test2.wordpress.test
          - blog0.wordpress.test
          - blog1.wordpress.test
          - blog2.wordpress.test
    volumes:
      - ./var/wordpress:/var/www/html
    working_dir: /var/www/html
    healthcheck:
      test: [ "CMD", "service", "apache2", "status" ]
      interval: 1s
      timeout: 10s
      retries: 5
  chrome:
    container_name: wpbrowser_php_${PHP_VERSION:-8.0}_chrome
    image: selenium/standalone-chrome:3.141.59-20210105
    networks:
      - test
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 1s
      timeout: 10s
      retries: 5
  codecept:
    container_name: wpbrowser_php_${PHP_VERSION:-8.0}_codeception
    user: "${USER_UID}:${USER_GID}"
    image: wp-browser-wordpress:php${PHP_VERSION:-8.0}-codeception
    build:
      context: ./config/containers/php
      args:
        PHP_VERSION: "${PHP_VERSION:-8.0}"
        USER_UID: "${USER_UID:-33}"
        USER_GID: "${USER_GID:-www-data}"
        USER_NAME: "${USER_NAME:-www-data}"
        TARGET: "codeception"
    depends_on:
      database:
        condition: service_healthy
      wordpress:
        condition: service_healthy
      chrome:
        condition: service_healthy
    environment:
      COMPOSER_CACHE_DIR: "${PWD}/var/cache/composer"
    networks:
      - test
    volumes:
      - "${PWD}:${PWD}"
    working_dir: "${PWD}"
    entrypoint: tail -f /dev/null
