version: "3"

networks:
  test:

services:

  db:
    image: mariadb
    networks:
      - test
    environment:
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    image: wordpress
    networks:
      test:
        aliases:
          - "wordpress.localhost"
          - "test1.wordpress.localhost"
          - "test2.wordpress.localhost"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_NAME: test
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define( 'WP_ALLOW_MULTISITE', true );
        define( 'MULTISITE', true );
        define( 'SUBDOMAIN_INSTALL', true );
        define( 'DOMAIN_CURRENT_SITE', 'wordpress.localhost' );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', 1 );
        define( 'BLOG_ID_CURRENT_SITE', 1 );
    volumes:
      - ./vendor/wordpress/wordpress:/var/www/html

  chrome:
    image: selenium/standalone-chrome:3.141.59-oxygen
    networks:
      - test

  codeception:
    image: lucatume/codeception:cc3.1.0
    networks:
      - test
    environment:
      WORDPRESS_DB_NAME: test
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      PHP_IDE_CONFIG: "serverName=${XDK:-wpbrowser}"
      XDEBUG_CONFIG: "idekey=${XDK:-wpbrowser} remote_enable=${XDR:-1} remote_host=${XDH:-host.docker.internal} remote_port=${XDP:-9001}"
    depends_on:
      - wordpress
      - chrome
    volumes:
    - .:/project
