version: "3.8"
networks:
  test:
    name: wpbrowser_php_${PHP_VERSION:-5.6}
services:
  database:
    container_name: wpbrowser_php_${PHP_VERSION:-5.6}_database
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    healthcheck:
      test: [ "CMD", "mysqlshow", "-uroot", "-ppassword",  "wordpress" ]
      interval: 1s
      timeout: 1s
      retries: 30
    networks:
      - test
  wordpress:
    container_name: wpbrowser_php_${PHP_VERSION:-5.6}_wordpress
    user: "${USER_UID}:${USER_GID}"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    image: wp-browser-wordpress:php${PHP_VERSION:-5.6}-apache
    build:
      context: ./_build/_container/wordpress
      args:
        PHP_VERSION: "${PHP_VERSION:-5.6}"
        USER_UID: "${USER_UID:-33}"
        USER_GID: "${USER_GID:-www-data}"
        USER_NAME: "${USER_NAME:-www-data}"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://wordpress.test" ]
      interval: 1s
      timeout: 1s
      retries: 30
    networks:
      test:
        aliases:
          - wordpress.test
          - one.wordpress.test
          - two.wordpress.test
          - test1.wordpress.test
          - test2.wordpress.test
          - blog0.wordpress.test
          - blog1.wordpress.test
          - blog2.wordpress.test
    extra_hosts:
      - "wordpress.test:127.0.0.1"
      - "one.wordpress.test:127.0.0.1"
      - "two.wordpress.test:127.0.0.1"
      - "test1.wordpress.test:127.0.0.1"
      - "test2.wordpress.test:127.0.0.1"
      - "blog0.wordpress.test:127.0.0.1"
      - "blog1.wordpress.test:127.0.0.1"
      - "blog2.wordpress.test:127.0.0.1"
    volumes:
      - ./_wordpress:/var/www/html
      - "${PWD}:${PWD}"
  chrome:
    container_name: wpbrowser_php_${PHP_VERSION:-5.6}_chrome
    image: selenium/standalone-chrome:3.141.59-20210105
    networks:
      - test
    depends_on:
      wordpress:
        condition: service_healthy
