version: '3.2'

services:

  chromedriver:
    image: selenium/standalone-chrome
    container_name: wpbrowser_chromedriver
    links:
      - wp
    extra_hosts:
      - "wp.test:${WP_CONTAINER_IP:-127.0.0.1}"
      - "test1.wp.test:${WP_CONTAINER_IP:-127.0.0.1}"
      - "test2.wp.test:${WP_CONTAINER_IP:-127.0.0.1}"
    ports:
      - "4445:4444"

  db:
    image: mariadb:latest
    container_name: wpbrowser_db
    ports:
      # listen for external connections on port 3306
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: test_site
      MYSQL_USER: wordrpess
      MYSQL_PASSWORD: wordpress
    command: mysqld --debug-no-sync

  wp:
    image: wordpress:php5.6
    container_name: wpbrowser_wp
    depends_on:
      - db
    ports:
      # listen for external connections on port 3306
      - "80:80"
    environment:
      WORDPRESS_DB_NAME: test_site
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
    volumes:
      # bind the core WordPress folder to the /var/www/html folder
      - ./../vendor/wordpress/wordpress:/var/www/html
      # bind the root folder to the /project folder
      - ./..:/project
