name: CI

on: [push]

jobs:
  test:
    name: Run tests on PHP ${{ matrix.php_version }}, CC ${{ codeception_version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php_version: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4' ]
        codeception_version: [ '2.5', '3.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ matrix.php_version }}-cc-${{ matrix.codeception_version }}-${{ hashFiles('**/composer.json') }}
      - name: Prepare Composer dependencies
        run: test -d vendor || _build/vendor_prepare.sh ${{ matrix.php_version }} ${{ matrix.codeception_version }}
      - name: Run tests
        env:
          CI_PHP_VERSION: ${{ strategy.php_version }}
          CI_CODECEPTION_VERSION: ${{ strategy.codeception_version }}
        run: make test
