name: docs
on:
  push:
    paths:
        - 'docs/**'
        - mkdocs.yml
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt-get install pngquant
      - run: pip install git+https://${MKDOCS_GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git pillow
      - run: mkdocs gh-deploy --force
env:
  MKDOCS_GH_TOKEN: ${{ secrets.MKDOCS_GH_TOKEN }}
