# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrate"

on:  # yamllint disable-line rule:truthy
    push:
        branches:
        - "master"
        - "version-4/minimum-compat-pass"
    pull_request: null
# Add [skip ci] to commit message to skip CI.

permissions: {}  # yamllint disable-line rule:braces

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    static_analysis:
        name: "Static Analysis"
        runs-on: "ubuntu-22.04"
        steps:
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@v2"
            with:
                php-version: "8.0"
                coverage: "none"
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Validate Composer configuration"
            run: "composer validate --no-interaction --strict"
        -
            name: "Install dependencies"
            uses: "ramsey/composer-install@v2"
            with:
                dependency-versions: "highest"
        -
            name: "Check PSR-4 mapping"
            run: "composer dump-autoload --no-interaction --optimize --strict-psr"
        -
            name: "Install WordPress extension for PHPStan"
            run: "composer require --dev szepeviktor/phpstan-wordpress"
        -
            name: "Perform static analysis"
            run: "composer exec -- phpstan"
