# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Static Analysis"

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'src/**'
      - 'includes/**'
      - 'tests/**'
      - 'composer.json'
      - '.github/workflows/static-analysis.yml'
  push:
    paths:
      - 'src/**'
      - 'includes/**'
      - 'tests/**'
      - 'composer.json'
      - '.github/workflows/static-analysis.yml'
    branches:
      - "master"

permissions:
  contents: "read"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  static_analysis:
    name: "Static Analysis"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"
          coverage: "none"
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      - name: "Validate Composer configuration"
        run: "composer validate --no-interaction --strict"
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
      - name: "Check PSR-4 mapping"
        run: "composer dump-autoload --no-interaction --optimize --strict-psr"
      - name: "Run PHPHStan"
        run: "composer run stan"
      - name: "Run PHPCBF"
        continue-on-error: true
        run: "composer run cs-fix"
      - name: "Run PHP Code Sniffer"
        run: "composer run cs"
