name: Static Analysis

on: [push]

jobs:

  lint-on-56:
    name: PHP 5.6 lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: make lint

  phpcs:
    name: phpcs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sniff files
        run: make phpcs

  phpstsan:
    name: phpstan
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set src directory hash
        run: echo "SRC_HASH=$(_build/dir_hash.sh src)" >> $GITHUB_ENV
      - name: Cache Composer dependencies
        uses: gerbal/always-cache@v1
        with:
          path: vendor
          key: composer-5.6-cc-4.0-${{ hashFiles('**/composer.json') }}-${{ env.SRC_HASH }}
      - name: Install Composer dependencies
        run: make PHP_VERSION=5.6 CODECEPTION_MAJOR_VERSION=4 composer_install
      - name: Run PHPStan static analysis
        run: make PHP_VERSION=5.6 PHPSTAN_LEVEL=max phpstan
