name: Test
on: [ push ]
jobs:
  test_codeception_lt_4:
    strategy:
      matrix:
        php_version: [ '5.6', '7.4' ]
        codeception_version: [ 2, 3 ]
    name: PHP ${{ matrix.php_version }}, Codeception ${{ matrix.codeception_version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: _build/stack.sh -p${{ matrix.php_version }} build
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ./.cache/composer
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}-${{ matrix.codeception_version }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
          php_extensions: sockets pcntl gd zip
          version: 2.2
          command: update
          args: --with codeception/codeception:^${{ matrix.codeception_version }}.0 --with-all-dependencies
      - name: Test
        run: _build/stack.sh -p${{ matrix.php_version }} test
  test_codeception_4:
    strategy:
      matrix:
        php_version: [ '5.6', '7.4', '8.0', '8.1' ]
    name: PHP ${{ matrix.php_version }}, Codeception ${{ matrix.codeception_version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ./.cache/composer
          key: ${{ runner.os }}-${{ hashFiles('**/composer.codecept-4.json') }}-${{ matrix.codeception_version }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
          php_extensions: sockets pcntl gd zip
          version: 2.2
          command: update
          args: --with codeception/codeception:^4.0 --with-all-dependencies
      - name: Test
        run: _build/stack.sh -p${{ matrix.php_version }} test
