# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "master"

permissions:
  contents: "read"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        php_version: [ '8.0', '8.1', '8.2' ]
        suite:
          - acceptance
          - climodule
          - functional
          - muloader
          - unit
          - webdriver
          - wpcli_module
          - wploader_multisite
          - wploader_wpdb_interaction
          - wploadersuite
    name: ${{ matrix.suite }} php@${{ matrix.php_version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: uopz, sqlite3, gd
          ini-values: post_max_size=256M, max_execution_time=180, uopz.exit=1
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: var/cache/composer
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer update

      - name: Update ChromeDriver
        run: vendor/bin/codecept chromedriver:update --binary /usr/bin/google-chrome

      - name: Create var/wordpress directory
        run: mkdir -p var/wordpress

      - name: Start services
        run: vendor/bin/codecept dev:start

      - name: Setup WordPress
        run: php bin/setup-wp.php

      - name: Run tests
        id: test
        run: vendor/bin/codecept run ${{ matrix.suite }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: ${{ matrix.suite }}-php@${{ matrix.php_version }}-screenshots
          path: |
            var/_output/*.html
            var/_output/*.png
          retention-days: 3
