name: Test
on: [ push ]
jobs:
  test_codeception_lt_4:
    strategy:
      matrix:
        php_version: [ '5.6', '7.4' ]
        codeception_version: [ 2, 3 ]
        composer_version: [ 2 ]
    name: PHP ${{ matrix.php_version }}, CC ${{ matrix.codeception_version }}, Composer ${{ matrix.composer_version }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set src directory hash
        run: echo "SRC_HASH=$(_build/dir_hash.sh src)" >> $GITHUB_ENV
      - name: Cache Composer dependencies
        uses: gerbal/always-cache@v1
        with:
          path: vendor
          key: composer-${{ matrix.php_version }}-cc-${{ matrix.codeception_version }}-composer-v1-${{ hashFiles('**/composer.json') }}-${{ env.SRC_HASH }}
      - name: Build
        run: make build
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          CODECEPTION_MAJOR_VERSION: ${{ matrix.codeception_version }}
          COMPOSER_VERSION: ${{ matrix.composer_version }}
      - name: Test
        run: make test
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          CODECEPTION_MAJOR_VERSION: ${{ matrix.codeception_version }}
          COMPOSER_VERSION: ${{ matrix.composer_version }}
  test_codeception_4:
    strategy:
      matrix:
        php_version: [ '5.6', '7.4', '8.0' ]
        codeception_version: [ 4 ]
        composer_version: [ 2 ]
    name: PHP ${{ matrix.php_version }}, CC ${{ matrix.codeception_version }}, Composer ${{ matrix.composer_version }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set src directory hash
        run: echo "SRC_HASH=$(_build/dir_hash.sh src)" >> $GITHUB_ENV
      - name: Cache Composer dependencies
        uses: gerbal/always-cache@v1
        with:
          path: vendor
          key: composer-${{ matrix.php_version }}-cc-${{ matrix.codeception_version }}-composer-v1-${{ hashFiles('**/composer.json') }}-${{ env.SRC_HASH }}
      - name: Build
        run: make build
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          CODECEPTION_MAJOR_VERSION: ${{ matrix.codeception_version }}
          COMPOSER_VERSION: ${{ matrix.composer_version }}
      - name: Test
        run: make test
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          CODECEPTION_MAJOR_VERSION: ${{ matrix.codeception_version }}
          COMPOSER_VERSION: ${{ matrix.composer_version }}
